export const portfolio={
person:{name:'Adhithi Mudaliyar',nickname:'Addy',school:'University of South Florida',degree:'B.S. Computer Science & Economics',graduation:'May 2028',email:'adhithimudaliyar@gmail.com',github:'https://github.com/2005ACE',linkedin:'https://www.linkedin.com/in/adhithi-mudaliyar/',resume:'/resume.pdf'},
skills:[
{title:'AI & Machine Learning',items:['Python','scikit-learn','XGBoost','PyTorch','Hugging Face Transformers','RAG','SHAP']},
{title:'Software & Data',items:['Java','JavaScript','SQL','PostgreSQL','Pandas','NumPy','Spark','Airflow','Databricks','FastAPI','REST APIs']},
{title:'Embedded Systems',items:['C / C++','STM32','Raspberry Pi','Linux','UART','PWM / DAC','ADC pressure readings']},
{title:'Tools & Testing',items:['Git / GitHub','Azure DevOps','Docker','pytest','AWS S3','AWS SageMaker','Agile','AI-assisted development']}
],
projects:[
{name:'ToxiScope',summary:'Investigating molecular toxicity with machine learning and scientific literature.',diagnosis:'Toxicity evidence is fragmented across unstructured biomedical literature, while labeled compound data is expensive to produce.',procedure:'Built a PubMed retrieval workflow combining BM25 and dense retrieval, alongside active-learning toxicity models in Python and PyTorch.',outcome:'Matched the baseline ROC-AUC with 40% fewer labeled compounds and verified citations across 50 queries.',tools:['Python','PyTorch','Hugging Face','RAG','Streamlit'],links:[]},
{name:'MedLens',summary:'Making sense of Medicare prescription patterns and spending.',diagnosis:'Large public CMS datasets contain useful patterns, but their scale and structure make them difficult to investigate directly.',procedure:'Built Airflow and S3 pipelines over five million CMS Part D records across three annual releases, then surfaced findings through Power BI and Streamlit.',outcome:'The XGBoost forecast beat a last-year baseline by 10% MAE on time-based holdouts. Pytest validation gates protected each pipeline stage.',tools:['Python','SQL','Airflow','Spark','Databricks','AWS S3','XGBoost'],links:[]},
{name:'Diabetes Risk Intelligence',summary:'Predicting diabetes risk and understanding what drives the prediction.',diagnosis:'Risk predictions are more useful when their reasoning can be examined and their behavior can be tested.',procedure:'Built a calibrated XGBoost workflow with SHAP explanations, served through a containerized FastAPI service on AWS SageMaker.',outcome:'Reached 0.89 held-out ROC-AUC and served predictions in under 120 ms, with pytest coverage for retraining and API behavior.',tools:['XGBoost','SHAP','FastAPI','Docker','AWS SageMaker','pytest'],links:[]}
],
experience:[
{org:'Center for Advanced Medical Learning and Simulation',role:'Research Assistant',date:'Sep 2026–Present',summary:'Building immersive clinical training simulations, research data pipelines, and AI-driven virtual patients.',details:['Build immersive VR/AR training simulations for clinical education in Dr. Shannon Bailey’s human factors lab.','Develop data pipelines that turn XR trainee interaction data into research-ready datasets.','Prototype generative AI tools for healthcare simulation, including LLM-driven virtual patients.']},
{org:'Elevate Healthcare',role:'Firmware Engineering Intern',date:'May–Aug 2026',summary:'Built and tested firmware connecting physiological signals, device communication, and clinical audio in a healthcare simulator.',details:['Built Python/Linux test tooling and embedded C/C++ to integrate and validate four healthcare simulation subsystems.','Worked with Raspberry Pi and STM32 hardware, UART communication, PWM/DAC waveforms, ADC pressure readings, and clinical audio.','Used Claude Code and GitHub Copilot to navigate embedded codebases and draft test harnesses, reviewing generated changes against subsystem specifications before merge.','Documented reproducible integration tests and handoff procedures for the engineering team.','Tracked defects and validated device behavior across Agile sprints using Git and Azure DevOps.']},
{org:'USF Technology Transfer',role:'Student Assistant',date:'Jul 2025–Present',summary:'Kept technology records, patent documentation, and financial tracking organized for university research commercialization.',details:['Managed technology marketing spreadsheets in Minuet and organized licensed and closed technology files in Box.','Collected and reviewed patent reference materials, standardized file naming, and prepared reference packages.','Processed invoice batches, generated cost receipts in Bull Marketplace, merged supporting PDFs, and updated Excel tracking sheets.']},
{org:'ACM at USF',role:'Technical Lead · Marketing Shadow',date:'Apr 2025–Apr 2026 · Sep 2024–Apr 2025',summary:'Progressed from marketing support to technical leadership in USF’s computing community.',details:['Technical Lead · Apr 2025–Apr 2026.','Marketing Shadow · Sep 2024–Apr 2025.']},
{org:'USF Digital Engagement Center',role:'Student Engagement Specialist',date:'Oct 2024–May 2025',summary:'Connected with students, alumni, and community members through direct outreach, using engagement data to improve how we reached them.',details:['Built and maintained relationships with students, alumni, and community members to support university initiatives.','Conducted outreach through phone, email, and digital platforms.','Tracked engagement metrics to assess effectiveness, refine outreach, and report impact.','Coordinated with teammates to maintain professional, consistent communication.']}
],
research:[
{title:'Immersive Training & Virtual Patients',org:'Dr. Shannon Bailey’s Human Factors Lab · CAMLS',summary:'Exploring how immersive environments and AI-driven virtual patients can support clinical education, with trainee interaction data helping researchers study the learning process.',question:'How can immersive training data and AI-driven virtual patients support better clinical education?',contribution:'Building XR simulations, research-ready interaction-data pipelines, and generative AI prototypes for simulation.',methods:'VR/AR development · XR interaction data · LLM-driven virtual patients',output:'Ongoing research support.'},
{title:'Harmonizing Multimodal Aging Data for Cognitive Decline',org:'TASH · Prof. Yu Sun',summary:'Harmonizing multimodal aging datasets so researchers can study patterns associated with cognitive decline.',question:'How can measurements from different aging cohorts be made comparable enough to study cognitive decline?',contribution:'Resolved incompatible ADNI and HABS-HD schemas, authored harmonization pipelines, and delivered classification workflows in Python.',methods:'Pandas · scikit-learn · five-fold cross-validation · error analysis',output:'Poster presentation.'}
]};
