export const portfolio={
person:{name:'Adhithi Mudaliyar',nickname:'Addy',school:'University of South Florida',degree:'B.S. Computer Science & Economics',graduation:'May 2028',location:'Tampa, Florida',email:'adhithimudaliyar@gmail.com',github:'https://github.com/2005ACE',linkedin:'https://www.linkedin.com/in/adhithi-mudaliyar/',resume:'/resume.pdf'},
skills:[
{title:'AI & machine learning',items:['Python','scikit-learn','XGBoost','PyTorch','Hugging Face Transformers','RAG','SHAP']},
{title:'Software & data',items:['Java','JavaScript','SQL','PostgreSQL','Pandas','NumPy','Spark','Airflow','Databricks','FastAPI','REST APIs']},
{title:'Embedded systems',items:['C / C++','STM32','Raspberry Pi','Linux','Hardware communication','Physiological signals']},
{title:'Development tools',items:['Git / GitHub','Azure DevOps','Docker','pytest','AWS S3','AWS SageMaker','Agile','AI-assisted development']}
],
projects:[
{index:'01',name:'ToxiScope',type:'Computational toxicology · 2026',summary:'A machine-learning and literature-retrieval system for investigating compound toxicity with sourced evidence.',diagnosis:'Toxicity evidence is fragmented across unstructured biomedical literature, while labeled compound data is expensive to produce.',procedure:'Built a PubMed retrieval workflow combining BM25 and dense retrieval, alongside active-learning toxicity models in Python and PyTorch.',findings:'Matched the baseline ROC-AUC with 40% fewer labeled compounds and verified citations across 50 queries.',tools:['Python','PyTorch','Hugging Face','RAG','Streamlit'],links:[]},
{index:'02',name:'MedLens',type:'Healthcare analytics · 2026',summary:'A data system for exploring Medicare prescription use, spending, and one-year-ahead forecasting.',diagnosis:'Large public CMS datasets contain useful patterns, but their scale and structure make them difficult to investigate directly.',procedure:'Built Airflow and S3 pipelines over five million CMS Part D records across three annual releases, then surfaced findings through Power BI and Streamlit.',findings:'The XGBoost forecast beat a last-year baseline by 10% MAE on time-based holdouts. Pytest validation gates protected each pipeline stage.',tools:['Python','SQL','Airflow','Spark','Databricks','AWS S3','XGBoost'],links:[]},
{index:'03',name:'Diabetes Risk Intelligence System',type:'Explainable ML · 2025',summary:'A deployed risk-prediction service designed to pair model output with inspectable explanations.',diagnosis:'Risk predictions are more useful when their reasoning can be examined and their behavior can be tested.',procedure:'Built a calibrated XGBoost workflow with SHAP explanations, served through a containerized FastAPI service on AWS SageMaker.',findings:'Reached 0.89 held-out ROC-AUC and served predictions in under 120 ms, with pytest coverage for retraining and API behavior.',tools:['XGBoost','SHAP','FastAPI','Docker','AWS SageMaker','pytest'],links:[]}
],
experience:[
{date:'Sep 2026 — present',org:'USF Health · CAMLS',role:'Research Assistant',body:'Validate experimental logging and simulation behavior through end-to-end testing of an XR medical-training platform. Standardize simulation errors, completion times, and device conditions into documented, analysis-ready Python pipelines.'},
{date:'Apr — Sep 2026',org:'University of South Florida · Prof. Yu Sun',role:'Student Researcher',body:'Harmonized ADNI and HABS-HD schemas into a 32-feature multimodal dataset used by five research teams. Built reproducible classification workflows with cross-validation and error analysis.'},
{date:'May — Aug 2026',org:'Elevate Healthcare',role:'Software / Firmware Engineer Intern',body:'Built Python and embedded C/C++ tooling to integrate and validate four healthcare simulation subsystems across Raspberry Pi, STM32, hardware communication, and physiological signals. Documented test and handoff procedures adopted by seven engineers.'},
{date:'Apr 2025 — present',org:'Association for Computing Machinery · USF',role:'Technical Lead',body:'Lead a ten-member technical team delivering AI and software workshops to more than fifty students weekly. Mentor peers in debugging, testing, and Git-based collaboration.'}
],
research:[
{code:'R.01',title:'Multimodal aging data & cognitive decline',question:'How can measurements from different aging cohorts be made comparable enough to study cognitive decline?',role:'Resolved incompatible ADNI and HABS-HD schemas, authored harmonization pipelines, and delivered classification workflows in Python.',methods:'Pandas · scikit-learn · five-fold cross-validation · error analysis',output:'Analysis-ready 32-feature dataset and reproducible workflows for five research teams. No publication or poster is listed on the current résumé.'},
{code:'R.02',title:'XR medical-training research',question:'How can simulation data remain trustworthy from platform behavior through downstream analysis?',role:'Test experimental logging end to end and standardize simulation errors, completion times, and device conditions for research collaborators.',methods:'XR platform testing · Python pipelines · data-integrity checks',output:'Ongoing work. Confirmed publications, posters, and presentations are not listed on the current résumé.'}
]};
