import './styles.css';
import { portfolio as data } from './content.js';

const {person}=data;
const portraitSrc='/images/profile-photo.jpeg';
const chips=(items)=>items.map((item)=>`<span>${item}</span>`).join('');
const list=(items)=>`<ul>${items.map((item)=>`<li>${item}</li>`).join('')}</ul>`;

document.querySelector('#app').innerHTML=`
<header class="topbar" data-header>
<button class="nav-toggle" type="button" aria-expanded="false" aria-controls="nav"><span class="sr-only">Open menu</span><i></i><i></i></button>
<nav id="nav" aria-label="Primary navigation"><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#research">Research</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav>
<a class="resume-download" href="${person.resume}" download="Adhithi-Mudaliyar-Resume.pdf">Résumé ↓</a>
 </header>
<main id="main"><aside class="anatomy-stage" aria-label="Animated anatomical skeleton"><div class="stage-frame"><canvas id="anatomy-canvas"></canvas><img class="skeleton-fallback" src="/images/skeleton-fallback.png" alt=""/><div class="load-status" aria-live="polite">Loading anatomy…</div><button class="motion-toggle" type="button" aria-pressed="false"><span class="motion-dot"></span><span data-motion-label>Pause motion</span></button><a class="model-credit" href="https://github.com/yamz8/human-body-simulator" target="_blank" rel="noopener">Model attribution ↗</a></div></aside><div class="scroll-area"><div class="story-column">
<section class="panel hero" id="home" data-view="full" aria-labelledby="hero-title"><p class="hero-name">${person.name}</p><h1 id="hero-title">Somewhere between a stethoscope and a line of code is where my curiosity lives.</h1><p class="hero-copy">Hi, I’m Addy. AI student, curious by default. Big on healthcare, bigger on BTS.</p></section>
<section class="panel" id="about" data-view="chest" aria-labelledby="about-title"><header class="section-head"><p>About</p><h2 id="about-title">Under the Skin</h2></header><div class="about-layout"><div class="prose"><p>AI helps me understand how machines learn. Economics keeps me wondering why humans do what they do. I study both at USF, with a particular interest in what they can bring to healthcare and the people who depend on it.</p><p>I like breaking down complicated things and turning ‘what if?’ into something I can build. One question usually leads to another, which explains both my range of interests and the number of tabs I have open.</p><p>Away from those tabs, I’m skating, solving a Rubik’s Cube, or watching Modern Family. Always up for a good conversation, a new rabbit hole, or a spontaneous plan that interrupts my very detailed schedule.</p></div>${portraitSrc?`<div class="portrait-exit" data-portrait-exit><div class="portrait-reveal" data-portrait-reveal><img class="about-portrait portrait-base" src="${portraitSrc}" alt="" aria-hidden="true"/><img class="about-portrait portrait-color" src="${portraitSrc}" alt="Adhithi Mudaliyar"/><span class="portrait-scan" aria-hidden="true"></span><span class="portrait-corners" aria-hidden="true"><i></i><i></i><i></i><i></i></span></div><div class="portrait-diagnostic"><button type="button" class="portrait-replay" data-portrait-replay>Replay photo scan</button><span class="portrait-build">build 34ac32f</span><span class="portrait-status" data-portrait-status role="status" aria-live="polite">Scan ready</span></div></div>`:''}</div></section>
<section class="panel" id="experience" data-view="spine" aria-labelledby="experience-title"><header class="section-head"><p>Experience</p><h2 id="experience-title">Clinical History</h2></header><div class="entry-list">${data.experience.map((item,i)=>`<button class="entry-row" data-dialog-trigger="experience-${i}" type="button"><span class="entry-date">${item.date}</span><span class="entry-main"><strong>${item.role}</strong><em>${item.org}</em><span>${item.summary}</span></span><b aria-hidden="true">↗</b></button>`).join('')}</div></section>
<section class="panel" id="projects" data-view="outline" aria-labelledby="projects-title"><header class="section-head"><p>Projects</p><h2 id="projects-title">Anatomy of a Build</h2></header><div class="project-grid">${data.projects.map((item,i)=>`<article class="project-card"><div class="project-graphic graphic-${i}" aria-hidden="true">${i===0?'<svg viewBox="0 0 180 90"><path d="M25 45h35m60 0h35M60 45l30-25m0 25 30 25M60 45l30 25m0-25 30-25"/><circle cx="25" cy="45" r="6"/><circle cx="60" cy="45" r="6"/><circle cx="90" cy="20" r="6"/><circle cx="90" cy="70" r="6"/><circle cx="120" cy="45" r="6"/><circle cx="155" cy="45" r="6"/></svg>':i===1?'<svg viewBox="0 0 180 90"><path d="M18 70h145M28 70V38h20v32m10 0V25h20v45m10 0V48h20v22m10 0V32h20v38"/><path d="M24 20h130" opacity=".35"/></svg>':'<svg viewBox="0 0 180 90"><circle cx="35" cy="60" r="11"/><circle cx="90" cy="28" r="11"/><circle cx="145" cy="54" r="11"/><path d="M45 54 80 34m20 0 35 14"/><path d="M90 39v33" opacity=".5"/></svg>'}</div><button class="entry-row project-trigger" data-dialog-trigger="project-${i}" type="button"><span class="entry-main"><strong>${item.name}</strong><span>${item.summary}</span><div class="chip-row">${chips(item.tools.slice(0,5))}</div></span><b aria-hidden="true">↗</b></button></article>`).join('')}</div></section>
<section class="panel" id="research" data-view="skull" aria-labelledby="research-title"><header class="section-head"><p>Research</p><h2 id="research-title">Under the Microscope</h2></header><div class="entry-list research-entries">${data.research.map((item,i)=>`<button class="entry-row" data-dialog-trigger="research-${i}" type="button"><span class="entry-date">0${i+1}</span><span class="entry-main"><strong>${item.title}</strong><em>${item.org}</em><span>${item.summary}</span></span><b aria-hidden="true">↗</b></button>`).join('')}</div></section>
<section class="panel" id="skills" data-view="neural" aria-labelledby="skills-title"><header class="section-head"><p>Skills</p><h2 id="skills-title">The Nervous System</h2></header><div class="skill-list">${data.skills.map((group)=>`<article><h3>${group.title}</h3><p>${group.items.join(' · ')}</p></article>`).join('')}</div></section>
<section class="panel contact-panel" id="contact" data-view="contact" aria-labelledby="contact-title"><header class="section-head"><p>Contact</p><h2 id="contact-title">Let’s Synapse</h2></header><p class="contact-line">A project idea, a good question, or a BTS conversation that gets wildly out of hand?</p><div class="contact-actions"><a class="button primary" href="mailto:${person.email}">Say hello ↗</a><a class="button secondary" href="${person.linkedin}" target="_blank" rel="noopener">LinkedIn ↗</a><a class="button secondary" href="${person.github}" target="_blank" rel="noopener">GitHub ↗</a></div></section>
</div></div></main>
${data.experience.map((item,i)=>`<dialog class="detail-dialog" id="experience-${i}" aria-labelledby="experience-${i}-title"><button class="dialog-close" type="button" data-close-dialog aria-label="Close details">×</button><p class="dialog-kicker">Clinical History</p><h2 id="experience-${i}-title">${item.role}</h2><p class="dialog-meta">${item.org} · ${item.date}</p>${list(item.details)}</dialog>`).join('')}
${data.projects.map((item,i)=>`<dialog class="detail-dialog" id="project-${i}" aria-labelledby="project-${i}-title"><button class="dialog-close" type="button" data-close-dialog aria-label="Close details">×</button><p class="dialog-kicker">Anatomy of a Build</p><h2 id="project-${i}-title">${item.name}</h2><div class="dialog-section"><h3>The Diagnosis</h3><p>${item.diagnosis}</p></div><div class="dialog-section"><h3>The Procedure</h3><p>${item.procedure}</p></div><div class="dialog-section"><h3>The Outcome</h3><p>${item.outcome}</p></div></dialog>`).join('')}
${data.research.map((item,i)=>`<dialog class="detail-dialog" id="research-${i}" aria-labelledby="research-${i}-title"><button class="dialog-close" type="button" data-close-dialog aria-label="Close details">×</button><p class="dialog-kicker">Under the Microscope</p><h2 id="research-${i}-title">${item.title}</h2><p class="dialog-meta">${item.org}</p><div class="dialog-section"><h3>Question</h3><p>${item.question}</p></div><div class="dialog-section"><h3>Contribution</h3><p>${item.contribution}</p></div><div class="dialog-section"><h3>Methods</h3><p>${item.methods}</p></div><div class="dialog-section"><h3>Output</h3><p>${item.output}</p></div></dialog>`).join('')}
`;

const header=document.querySelector('[data-header]'),toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#nav');
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.querySelector('.sr-only').textContent=open?'Open menu':'Close menu';nav.classList.toggle('open',!open)});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.focus()}});

let dialogTrigger=null;
document.querySelectorAll('[data-dialog-trigger]').forEach(trigger=>trigger.addEventListener('click',()=>{dialogTrigger=trigger;const dialog=document.getElementById(trigger.dataset.dialogTrigger);dialog.showModal();document.body.classList.add('dialog-open');dialog.querySelector('[data-close-dialog]').focus()}));
document.querySelectorAll('.detail-dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{document.body.classList.remove('dialog-open');dialogTrigger?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.querySelector('[data-close-dialog]').addEventListener('click',()=>dialog.close())});

const scrollArea=document.querySelector('.scroll-area');const sections=[...document.querySelectorAll('[data-view]')],navLinks=[...nav.querySelectorAll('a[href^="#"]')];let activeView='full',ticking=false;
function setActiveSection(){const areaRect=scrollArea.getBoundingClientRect();const marker=scrollArea.clientHeight*.42;let active=sections[0];for(const section of sections){if(section.getBoundingClientRect().top-areaRect.top<=marker)active=section;else break}const view=active.dataset.view;if(view!==activeView){activeView=view;document.body.dataset.view=view;window.dispatchEvent(new CustomEvent('anatomy-view',{detail:view}))}const home=sections[0],about=sections[1];const span=Math.max(1,about.offsetTop-home.offsetTop);const progress=Math.max(0,Math.min(1,(scrollArea.scrollTop-home.offsetTop)/span));window.dispatchEvent(new CustomEvent('anatomy-progress',{detail:progress}));navLinks.forEach(link=>{const current=link.getAttribute('href')===`#${active.id}`;link.classList.toggle('active',current);if(current)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')});header.classList.toggle('scrolled',scrollArea.scrollTop>16);ticking=false}
navLinks.forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.getAttribute('href'));if(target){event.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}}));
scrollArea.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(setActiveSection);ticking=true}},{passive:true});addEventListener('resize',setActiveSection);setActiveSection();
const stage=document.querySelector('.anatomy-stage');
const portraitExit=document.querySelector('[data-portrait-exit]');const portraitReveal=document.querySelector('[data-portrait-reveal]');const portraitImage=portraitReveal?.querySelector('.portrait-color');const portraitStatus=document.querySelector('[data-portrait-status]');const replayPortrait=document.querySelector('[data-portrait-replay]');let portraitPlayed=false,portraitScanning=false,portraitPaused=matchMedia('(prefers-reduced-motion: reduce)').matches,portraitReady=!!portraitImage?.complete,portraitDecoded=!!portraitImage?.naturalWidth;let portraitFrame=0;
function setPortraitStatus(text){if(portraitStatus)portraitStatus.textContent=text}
if(portraitPaused)setPortraitStatus('Skipped: reduced motion enabled');
function completePortrait(){if(!portraitReveal)return;portraitScanning=false;portraitReveal.classList.remove('is-scanning');portraitReveal.classList.add('is-complete');setPortraitStatus(portraitPaused?'Skipped: motion paused or reduced':'Scan complete')}
function startPortraitScan(force=false,debugMidpoint=false){if(!portraitReveal||(!force&&portraitPlayed))return;if(!portraitReady){portraitImage?.addEventListener('load',()=>{portraitReady=true;portraitDecoded=true;startPortraitScan(force,debugMidpoint)},{once:true});return}if(!portraitDecoded){portraitDecoded=true;const decoded=portraitImage?.decode?.();if(decoded){Promise.race([decoded,new Promise(resolve=>setTimeout(resolve,250))]).finally(()=>startPortraitScan(force,debugMidpoint))}else startPortraitScan(force,debugMidpoint);return}portraitPlayed=true;if(portraitPaused){completePortrait();return}portraitScanning=true;portraitReveal.classList.remove('is-complete','is-faded','is-midpoint');if(debugMidpoint){portraitReveal.classList.add('is-midpoint');setPortraitStatus('Midpoint held')}else{setPortraitStatus('Scanning…');portraitReveal.classList.add('is-scanning')}}
portraitReveal?.addEventListener('animationend',event=>{if(event.animationName==='portrait-reveal')completePortrait()});
addEventListener('anatomy-motion-paused',event=>{portraitPaused=event.detail;if(portraitPaused){completePortrait();setPortraitStatus('Skipped: motion paused')}else setPortraitStatus('Motion enabled — replay available')});
replayPortrait?.addEventListener('click',()=>{portraitPlayed=false;portraitReveal?.classList.remove('is-complete','is-scanning','is-faded','is-midpoint');setPortraitStatus('Starting…');setTimeout(()=>startPortraitScan(true,true),150)});
function updatePortrait(){portraitFrame=0;if(!portraitExit)return;const area=scrollArea.getBoundingClientRect();const about=document.querySelector('#about').getBoundingClientRect();const portrait=portraitExit.getBoundingClientRect();const top=about.top-area.top;const height=area.height;const visibleHeight=Math.max(0,Math.min(portrait.bottom,area.bottom)-Math.max(portrait.top,area.top));const portraitVisible=visibleHeight/Math.max(1,portrait.height)>=.5;const aboutActive=top<height*.16&&top>-height*.1;if(aboutActive&&portraitVisible&&!portraitPlayed)startPortraitScan();if(portraitScanning&&(!portraitVisible||top<height*.05)&&top<0)completePortrait();const exitProgress=Math.max(0,Math.min(1,-top/(height*.62)));portraitExit.style.opacity=String(1-exitProgress);portraitExit.style.transform=`translateY(${-16*exitProgress}px)`}
function queuePortrait(){if(!portraitFrame)portraitFrame=requestAnimationFrame(updatePortrait)}scrollArea.addEventListener('scroll',queuePortrait,{passive:true});addEventListener('resize',queuePortrait);queuePortrait();
const loadAnatomy=()=>import('./scene.js').then(({initAnatomyStage})=>initAnatomyStage()).catch(()=>{document.documentElement.classList.add('no-webgl');const status=document.querySelector('.load-status');if(status)status.textContent='Static anatomy'});if('requestIdleCallback' in window)requestIdleCallback(loadAnatomy,{timeout:900});else setTimeout(loadAnatomy,60);
