import './styles.css';
import { portfolio as data } from './content.js';

const {person}=data;
const chips=(items)=>items.map((item)=>`<span>${item}</span>`).join('');
const list=(items)=>`<ul>${items.map((item)=>`<li>${item}</li>`).join('')}</ul>`;

document.querySelector('#app').innerHTML=`
<header class="topbar" data-header><a class="wordmark" href="#home" aria-label="Addy, back to top">Addy.</a>
<button class="nav-toggle" type="button" aria-expanded="false" aria-controls="nav"><span class="sr-only">Open menu</span><i></i><i></i></button>
<nav id="nav" aria-label="Primary navigation"><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#research">Research</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav>
<a class="resume-link" href="${person.resume}" target="_blank" rel="noopener">Résumé <span>↗</span></a></header>
<main id="main"><div class="page-grid"><div class="story-column">
<section class="panel hero" id="home" data-view="full" aria-labelledby="hero-title"><p class="hero-name">${person.name}</p><h1 id="hero-title">Somewhere between a stethoscope and a line of code is where my curiosity lives.</h1><p class="hero-copy">Hi, I’m Addy. AI student, curious by default. Big on healthcare, bigger on BTS.</p></section>
<section class="panel" id="about" data-view="chest" aria-labelledby="about-title"><header class="section-head"><p>About</p><h2 id="about-title">Under the Skin</h2></header><div class="prose"><p>AI helps me understand how machines learn. Economics keeps me wondering why humans do what they do. I study both at USF, with a particular interest in what they can bring to healthcare and the people who depend on it.</p><p>I like breaking down complicated things and turning ‘what if?’ into something I can build. One question usually leads to another, which explains both my range of interests and the number of tabs I have open.</p><p>Away from those tabs, I’m skating, solving a Rubik’s Cube, or watching Modern Family. Always up for a good conversation, a new rabbit hole, or a spontaneous plan that interrupts my very detailed schedule.</p></div></section>
<section class="panel" id="experience" data-view="spine" aria-labelledby="experience-title"><header class="section-head"><p>Experience</p><h2 id="experience-title">Clinical History</h2></header><div class="entry-list">${data.experience.map((item,i)=>`<button class="entry-row" data-dialog-trigger="experience-${i}" type="button"><span class="entry-date">${item.date}</span><span class="entry-main"><strong>${item.role}</strong><em>${item.org}</em><span>${item.summary}</span></span><b aria-hidden="true">↗</b></button>`).join('')}</div></section>
<section class="panel" id="projects" data-view="outline" aria-labelledby="projects-title"><header class="section-head"><p>Projects</p><h2 id="projects-title">Anatomy of a Build</h2></header><div class="entry-list">${data.projects.map((item,i)=>`<button class="entry-row" data-dialog-trigger="project-${i}" type="button"><span class="entry-date">${String(i+1).padStart(2,'0')}</span><span class="entry-main"><strong>${item.name}</strong><span>${item.summary}</span><div class="chip-row">${chips(item.tools)}</div></span><b aria-hidden="true">↗</b></button>`).join('')}</div></section>
<section class="panel" id="research" data-view="skull" aria-labelledby="research-title"><header class="section-head"><p>Research</p><h2 id="research-title">Under the Microscope</h2></header><div class="entry-list research-entries">${data.research.map((item,i)=>`<button class="entry-row" data-dialog-trigger="research-${i}" type="button"><span class="entry-date">0${i+1}</span><span class="entry-main"><strong>${item.title}</strong><em>${item.org}</em><span>${item.summary}</span></span><b aria-hidden="true">↗</b></button>`).join('')}</div></section>
<section class="panel" id="skills" data-view="neural" aria-labelledby="skills-title"><header class="section-head"><p>Skills</p><h2 id="skills-title">The Nervous System</h2></header><div class="skill-list">${data.skills.map((group)=>`<article><h3>${group.title}</h3><p>${group.items.join(' · ')}</p></article>`).join('')}</div></section>
<section class="panel contact-panel" id="contact" data-view="contact" aria-labelledby="contact-title"><header class="section-head"><p>Contact</p><h2 id="contact-title">Let’s Synapse</h2></header><p class="contact-line">A project idea, a good question, or a BTS conversation that gets wildly out of hand?</p><div class="contact-actions"><a class="button primary" href="mailto:${person.email}">Say hello ↗</a><a class="button secondary" href="${person.linkedin}" target="_blank" rel="noopener">LinkedIn ↗</a><a class="button secondary" href="${person.github}" target="_blank" rel="noopener">GitHub ↗</a></div></section>
</div><aside class="anatomy-stage" aria-label="Animated anatomical skeleton"><div class="stage-frame"><canvas id="anatomy-canvas"></canvas><img class="skeleton-fallback" src="/images/skeleton-fallback.png" alt=""/><div class="load-status" aria-live="polite">Loading anatomy…</div><button class="motion-toggle" type="button" aria-pressed="false"><span class="motion-dot"></span><span data-motion-label>Pause motion</span></button><a class="model-credit" href="https://github.com/yamz8/human-body-simulator" target="_blank" rel="noopener">Model attribution ↗</a></div></aside></div></main>
${data.experience.map((item,i)=>`<dialog class="detail-dialog" id="experience-${i}" aria-labelledby="experience-${i}-title"><button class="dialog-close" type="button" data-close-dialog aria-label="Close details">×</button><p class="dialog-kicker">Clinical History</p><h2 id="experience-${i}-title">${item.role}</h2><p class="dialog-meta">${item.org} · ${item.date}</p>${list(item.details)}</dialog>`).join('')}
${data.projects.map((item,i)=>`<dialog class="detail-dialog" id="project-${i}" aria-labelledby="project-${i}-title"><button class="dialog-close" type="button" data-close-dialog aria-label="Close details">×</button><p class="dialog-kicker">Anatomy of a Build</p><h2 id="project-${i}-title">${item.name}</h2><div class="dialog-section"><h3>The Diagnosis</h3><p>${item.diagnosis}</p></div><div class="dialog-section"><h3>The Procedure</h3><p>${item.procedure}</p></div><div class="dialog-section"><h3>The Outcome</h3><p>${item.outcome}</p></div></dialog>`).join('')}
${data.research.map((item,i)=>`<dialog class="detail-dialog" id="research-${i}" aria-labelledby="research-${i}-title"><button class="dialog-close" type="button" data-close-dialog aria-label="Close details">×</button><p class="dialog-kicker">Under the Microscope</p><h2 id="research-${i}-title">${item.title}</h2><p class="dialog-meta">${item.org}</p><div class="dialog-section"><h3>Question</h3><p>${item.question}</p></div><div class="dialog-section"><h3>Contribution</h3><p>${item.contribution}</p></div><div class="dialog-section"><h3>Methods</h3><p>${item.methods}</p></div><div class="dialog-section"><h3>Output</h3><p>${item.output}</p></div></dialog>`).join('')}
<footer><span>© ${new Date().getFullYear()} ${person.name}</span><span>Designed with a little backbone.</span><a href="#home">Back to top ↑</a></footer>`;

const header=document.querySelector('[data-header]'),toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#nav');
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.querySelector('.sr-only').textContent=open?'Open menu':'Close menu';nav.classList.toggle('open',!open)});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.focus()}});

let dialogTrigger=null;
document.querySelectorAll('[data-dialog-trigger]').forEach(trigger=>trigger.addEventListener('click',()=>{dialogTrigger=trigger;const dialog=document.getElementById(trigger.dataset.dialogTrigger);dialog.showModal();document.body.classList.add('dialog-open');dialog.querySelector('[data-close-dialog]').focus()}));
document.querySelectorAll('.detail-dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{document.body.classList.remove('dialog-open');dialogTrigger?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.querySelector('[data-close-dialog]').addEventListener('click',()=>dialog.close())});

const sections=[...document.querySelectorAll('[data-view]')],navLinks=[...nav.querySelectorAll('a[href^="#"]')];let activeView='full',ticking=false;
function setActiveSection(){const marker=innerHeight*.42;let active=sections[0];for(const section of sections){if(section.getBoundingClientRect().top<=marker)active=section;else break}const view=active.dataset.view;if(view!==activeView){activeView=view;document.body.dataset.view=view;window.dispatchEvent(new CustomEvent('anatomy-view',{detail:view}))}navLinks.forEach(link=>{const current=link.getAttribute('href')===`#${active.id}`;link.classList.toggle('active',current);if(current)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')});header.classList.toggle('scrolled',scrollY>16);ticking=false}
addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(setActiveSection);ticking=true}},{passive:true});addEventListener('resize',setActiveSection);setActiveSection();
const stage=document.querySelector('.anatomy-stage'),pageGrid=document.querySelector('.page-grid'),hero=document.querySelector('.hero'),mobile=matchMedia('(max-width: 760px)');
function placeStage(e){if(e.matches)hero.append(stage);else pageGrid.append(stage)}placeStage(mobile);mobile.addEventListener('change',placeStage);
const loadAnatomy=()=>import('./scene.js').then(({initAnatomyStage})=>initAnatomyStage()).catch(()=>{document.documentElement.classList.add('no-webgl');const status=document.querySelector('.load-status');if(status)status.textContent='Static anatomy'});if('requestIdleCallback' in window)requestIdleCallback(loadAnatomy,{timeout:900});else setTimeout(loadAnatomy,60);
